"""initial schema

Revision ID: 54b80c4cf6bf
Revises: 
Create Date: 2026-03-01 23:16:49.975201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b80c4cf6bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankroll_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('bankroll', sa.Float(), nullable=False),
    sa.Column('total_bets', sa.Integer(), nullable=False),
    sa.Column('total_won', sa.Integer(), nullable=False),
    sa.Column('total_lost', sa.Integer(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('is_backtest', sa.Boolean(), nullable=False),
    sa.Column('backtest_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('outcome_bet', sa.String(length=1), nullable=False),
    sa.Column('odds_at_bet', sa.Float(), nullable=False),
    sa.Column('odds_at_close', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('is_backtest', sa.Boolean(), nullable=False),
    sa.Column('backtest_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('football_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('league', sa.String(length=4), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('fthg', sa.Integer(), nullable=False),
    sa.Column('ftag', sa.Integer(), nullable=False),
    sa.Column('ftr', sa.String(length=1), nullable=False),
    sa.Column('hthg', sa.Integer(), nullable=True),
    sa.Column('htag', sa.Integer(), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('home_yellow', sa.Integer(), nullable=True),
    sa.Column('away_yellow', sa.Integer(), nullable=True),
    sa.Column('home_red', sa.Integer(), nullable=True),
    sa.Column('away_red', sa.Integer(), nullable=True),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('odds_away', sa.Float(), nullable=True),
    sa.Column('odds_home_close', sa.Float(), nullable=True),
    sa.Column('odds_draw_close', sa.Float(), nullable=True),
    sa.Column('odds_away_close', sa.Float(), nullable=True),
    sa.Column('max_odds_home', sa.Float(), nullable=True),
    sa.Column('max_odds_draw', sa.Float(), nullable=True),
    sa.Column('max_odds_away', sa.Float(), nullable=True),
    sa.Column('avg_odds_home', sa.Float(), nullable=True),
    sa.Column('avg_odds_draw', sa.Float(), nullable=True),
    sa.Column('avg_odds_away', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_date', 'football_matches', ['date'], unique=False)
    op.create_index('idx_match_league_season', 'football_matches', ['league', 'season'], unique=False)
    op.create_index('idx_match_teams', 'football_matches', ['home_team', 'away_team'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('prob_home', sa.Float(), nullable=True),
    sa.Column('prob_draw', sa.Float(), nullable=True),
    sa.Column('prob_away', sa.Float(), nullable=True),
    sa.Column('implied_home', sa.Float(), nullable=True),
    sa.Column('implied_draw', sa.Float(), nullable=True),
    sa.Column('implied_away', sa.Float(), nullable=True),
    sa.Column('edge_home', sa.Float(), nullable=True),
    sa.Column('edge_draw', sa.Float(), nullable=True),
    sa.Column('edge_away', sa.Float(), nullable=True),
    sa.Column('recommended_outcome', sa.String(length=1), nullable=True),
    sa.Column('recommended_stake_pct', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_index('idx_match_teams', table_name='football_matches')
    op.drop_index('idx_match_league_season', table_name='football_matches')
    op.drop_index('idx_match_date', table_name='football_matches')
    op.drop_table('football_matches')
    op.drop_table('bets')
    op.drop_table('bankroll_snapshots')
    # ### end Alembic commands ###
