"""add_campaign_model_and_bet_fields

Revision ID: a241498e35b4
Revises: 54b80c4cf6bf
Create Date: 2026-03-02 14:25:44.787260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a241498e35b4'
down_revision: Union[str, None] = '54b80c4cf6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initial_bankroll', sa.Float(), nullable=False),
    sa.Column('flat_stake', sa.Float(), nullable=False),
    sa.Column('min_edge', sa.Float(), nullable=False),
    sa.Column('min_model_prob', sa.Float(), nullable=True),
    sa.Column('min_odds', sa.Float(), nullable=True),
    sa.Column('max_odds', sa.Float(), nullable=True),
    sa.Column('allowed_outcomes', sa.String(length=20), nullable=True),
    sa.Column('excluded_leagues', sa.Text(), nullable=True),
    sa.Column('combo_mode', sa.Boolean(), nullable=False),
    sa.Column('combo_max_legs', sa.Integer(), nullable=False),
    sa.Column('combo_min_odds', sa.Float(), nullable=False),
    sa.Column('combo_max_odds', sa.Float(), nullable=False),
    sa.Column('combo_top_n', sa.Integer(), nullable=False),
    sa.Column('target_bankroll', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bets', sa.Column('league', sa.String(length=10), nullable=True))
    op.add_column('bets', sa.Column('campaign_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'campaign_id')
    op.drop_column('bets', 'league')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
